export const defaultUsers = [
  {
    name: 'Admin User',
    email: 'admin@techverse.com',
    password: 'Admin123',
    role: 'admin',
  },
  {
    name: 'Jane Doe',
    email: 'jane@techverse.com',
    password: 'Student123',
    role: 'user',
  },
]

export const defaultCategories = [
  { name: 'Audio' },
  { name: 'Wearables' },
  { name: 'Accessories' },
  { name: 'Gaming' },
  { name: 'Smartphones' },
  { name: 'Laptops' },
  { name: 'Cameras' },
  { name: 'Tablets' },
]

export const defaultProducts = [
  {
    name: 'SoundCore Wireless Earbuds',
    brand: 'TechVerse',
    category: 'Audio',
    description: 'Premium wireless earbuds with noise cancellation, punchy bass, and all-day battery life.',
    price: 129.99,
    oldPrice: 149.99,
    stock: 32,
    rating: 4.6,
    images: ['/products/earbuds.svg'],
    specifications: { battery: '8h playtime', connectivity: 'Bluetooth 5.3' },
  },
  {
    name: 'Nova Smartwatch',
    brand: 'TechVerse',
    category: 'Wearables',
    description: 'A sleek smartwatch with fitness tracking, heart rate monitoring, and a bright display.',
    price: 189.99,
    oldPrice: 219.99,
    stock: 18,
    rating: 4.4,
    images: ['/products/watch.svg'],
    specifications: { screen: '1.4 inch AMOLED', waterResistance: '5ATM' },
  },
  {
    name: 'Nova Charging Pad',
    brand: 'TechVerse',
    category: 'Accessories',
    description: 'Fast wireless charging pad for phones, earbuds, and other Qi-enabled devices.',
    price: 39.99,
    oldPrice: 49.99,
    stock: 45,
    rating: 4.2,
    images: ['/products/charging-pad.svg'],
    specifications: { power: '15W', compatibility: 'Qi-enabled devices' },
  },
  {
    name: 'Pulse Gaming Headset',
    brand: 'TechVerse',
    category: 'Gaming',
    description: 'Comfortable over-ear headset with surround sound and a noise-cancelling mic.',
    price: 159.99,
    oldPrice: 179.99,
    stock: 22,
    rating: 4.5,
    images: ['/products/headset.svg'],
    specifications: { mic: 'Detachable', sound: '7.1 virtual surround' },
  },
  {
    name: 'Aurora X Pro',
    brand: 'TechVerse',
    category: 'Smartphones',
    description: 'A clean everyday smartphone with a vibrant display, long battery life, and fast charging.',
    price: 499.99,
    oldPrice: 549.99,
    stock: 20,
    rating: 4.5,
    images: ['/products/phone.svg'],
    specifications: { display: '6.4 inch OLED', battery: '5000 mAh' },
  },
  {
    name: 'Vertex Book 14',
    brand: 'TechVerse',
    category: 'Laptops',
    description: 'Lightweight laptop for study, coding, and day-to-day college work.',
    price: 799.99,
    oldPrice: 899.99,
    stock: 14,
    rating: 4.7,
    images: ['/products/laptop.svg'],
    specifications: { cpu: 'Intel Core i5', memory: '16GB RAM' },
  },
  {
    name: 'Pixel Shot Camera',
    brand: 'TechVerse',
    category: 'Cameras',
    description: 'Compact mirrorless-style camera for creators, travel, and content projects.',
    price: 649.99,
    oldPrice: 729.99,
    stock: 11,
    rating: 4.3,
    images: ['/products/camera.svg'],
    specifications: { sensor: '24MP', video: '4K recording' },
  },
  {
    name: 'Aura Smart Speaker',
    brand: 'TechVerse',
    category: 'Audio',
    description: 'Compact smart speaker with clear sound, voice assistant support, and a clean design.',
    price: 89.99,
    oldPrice: 109.99,
    stock: 26,
    rating: 4.4,
    images: ['/products/speaker.svg'],
    specifications: { voice: 'Voice assistant', connectivity: 'Wi-Fi + Bluetooth' },
  },
  {
    name: 'Orbit Power Bank',
    brand: 'TechVerse',
    category: 'Accessories',
    description: 'Slim power bank with fast charging and enough capacity for a full day of use.',
    price: 34.99,
    oldPrice: 44.99,
    stock: 38,
    rating: 4.3,
    images: ['/products/powerbank.svg'],
    specifications: { capacity: '10000 mAh', output: '18W' },
  },
  {
    name: 'Slate Tab 11',
    brand: 'TechVerse',
    category: 'Tablets',
    description: 'Light tablet for notes, media, and daily college tasks with a sharp display.',
    price: 429.99,
    oldPrice: 469.99,
    stock: 16,
    rating: 4.5,
    images: ['/products/tablet.svg'],
    specifications: { display: '11 inch', storage: '128GB' },
  },
  {
    name: 'Neo Mechanical Keyboard',
    brand: 'TechVerse',
    category: 'Gaming',
    description: 'Compact mechanical keyboard with tactile switches and a minimal desk footprint.',
    price: 119.99,
    oldPrice: 139.99,
    stock: 21,
    rating: 4.6,
    images: ['/products/keyboard.svg'],
    specifications: { switches: 'Tactile', layout: '75%' },
  },
  {
    name: 'Air Mouse Pro',
    brand: 'TechVerse',
    category: 'Accessories',
    description: 'Wireless mouse with a soft matte finish, silent clicks, and quick response.',
    price: 24.99,
    oldPrice: 29.99,
    stock: 41,
    rating: 4.2,
    images: ['/products/mouse.svg'],
    specifications: { battery: '30 days', connectivity: '2.4 GHz' },
  },
]

