export const defaultUsers = [
  {
    name: 'Admin User',
    email: 'admin@techverse.com',
    password: 'Admin123',
    role: 'admin',
  },
  {
    name: 'Jane Doe',
    email: 'jane@techverse.com',
    password: 'Student123',
    role: 'user',
  },
]

export const defaultCategories = [
  { name: 'Audio' },
  { name: 'Wearables' },
  { name: 'Accessories' },
  { name: 'Gaming' },
  { name: 'Smartphones' },
  { name: 'Laptops' },
  { name: 'Cameras' },
  { name: 'Tablets' },
  { name: 'Daily Usage' },
  { name: 'Groceries' },
]

export const defaultProducts = [
  {
    name: 'SoundCore Wireless Earbuds',
    brand: 'TechVerse',
    category: 'Audio',
    description: 'Premium wireless earbuds with noise cancellation, punchy bass, and all-day battery life.',
    price: 1499,
    oldPrice: 2499,
    stock: 32,
    rating: 4.3,
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500&auto=format&fit=crop'],
    specifications: { battery: '8h playtime', connectivity: 'Bluetooth 5.3' },
  },
  {
    name: 'Nova Smartwatch',
    brand: 'TechVerse',
    category: 'Wearables',
    description: 'A sleek smartwatch with fitness tracking, heart rate monitoring, and a bright display.',
    price: 2999,
    oldPrice: 4999,
    stock: 18,
    rating: 4.2,
    images: ['https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?w=500&auto=format&fit=crop'],
    specifications: { screen: '1.4 inch AMOLED', waterResistance: '5ATM' },
  },
  {
    name: 'Nova Charging Pad',
    brand: 'TechVerse',
    category: 'Accessories',
    description: 'Fast wireless charging pad for phones, earbuds, and other Qi-enabled devices.',
    price: 999,
    oldPrice: 1499,
    stock: 45,
    rating: 4.1,
    images: ['https://images.unsplash.com/photo-1622445262465-2481c4574875?w=500&auto=format&fit=crop'],
    specifications: { power: '15W', compatibility: 'Qi-enabled devices' },
  },
  {
    name: 'Pulse Gaming Headset',
    brand: 'TechVerse',
    category: 'Gaming',
    description: 'Comfortable over-ear headset with surround sound and a noise-cancelling mic.',
    price: 2499,
    oldPrice: 3999,
    stock: 22,
    rating: 4.4,
    images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=500&auto=format&fit=crop'],
    specifications: { mic: 'Detachable', sound: '7.1 virtual surround' },
  },
  {
    name: 'Aurora X Pro',
    brand: 'TechVerse',
    category: 'Smartphones',
    description: 'A clean everyday smartphone with a vibrant display, long battery life, and fast charging.',
    price: 14999,
    oldPrice: 19999,
    stock: 20,
    rating: 4.5,
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500&auto=format&fit=crop'],
    specifications: { display: '6.4 inch OLED', battery: '5000 mAh' },
  },
  {
    name: 'Vertex Book 14',
    brand: 'TechVerse',
    category: 'Laptops',
    description: 'Lightweight laptop for study, coding, and day-to-day college work.',
    price: 42999,
    oldPrice: 54999,
    stock: 14,
    rating: 4.6,
    images: ['https://images.unsplash.com/photo-1496181130204-7552cc14ac1a?w=500&auto=format&fit=crop'],
    specifications: { cpu: 'Intel Core i5', memory: '16GB RAM' },
  },
  {
    name: 'Pixel Shot Camera',
    brand: 'TechVerse',
    category: 'Cameras',
    description: 'Compact mirrorless-style camera for creators, travel, and content projects.',
    price: 35999,
    oldPrice: 45999,
    stock: 11,
    rating: 4.4,
    images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500&auto=format&fit=crop'],
    specifications: { sensor: '24MP', video: '4K recording' },
  },
  {
    name: 'Aura Smart Speaker',
    brand: 'TechVerse',
    category: 'Audio',
    description: 'Compact smart speaker with clear sound, voice assistant support, and a clean design.',
    price: 1999,
    oldPrice: 2999,
    stock: 26,
    rating: 4.3,
    images: ['https://images.unsplash.com/photo-1589003077984-894e133dabab?w=500&auto=format&fit=crop'],
    specifications: { voice: 'Voice assistant', connectivity: 'Wi-Fi + Bluetooth' },
  },
  {
    name: 'Orbit Power Bank',
    brand: 'TechVerse',
    category: 'Accessories',
    description: 'Slim power bank with fast charging and enough capacity for a full day of use.',
    price: 1199,
    oldPrice: 1999,
    stock: 38,
    rating: 4.2,
    images: ['https://images.unsplash.com/photo-1601524909162-be87252be298?w=500&auto=format&fit=crop'],
    specifications: { capacity: '10000 mAh', output: '18W' },
  },
  {
    name: 'Slate Tab 11',
    brand: 'TechVerse',
    category: 'Tablets',
    description: 'Light tablet for notes, media, and daily college tasks with a sharp display.',
    price: 15999,
    oldPrice: 21999,
    stock: 16,
    rating: 4.5,
    images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500&auto=format&fit=crop'],
    specifications: { display: '11 inch', storage: '128GB' },
  },
  {
    name: 'Neo Mechanical Keyboard',
    brand: 'TechVerse',
    category: 'Gaming',
    description: 'Compact mechanical keyboard with tactile switches and a minimal desk footprint.',
    price: 2199,
    oldPrice: 3499,
    stock: 21,
    rating: 4.5,
    images: ['https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=500&auto=format&fit=crop'],
    specifications: { switches: 'Tactile', layout: '75%' },
  },
  {
    name: 'Air Mouse Pro',
    brand: 'TechVerse',
    category: 'Accessories',
    description: 'Wireless mouse with a soft matte finish, silent clicks, and quick response.',
    price: 699,
    oldPrice: 999,
    stock: 41,
    rating: 4.0,
    images: ['https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=500&auto=format&fit=crop'],
    specifications: { battery: '30 days', connectivity: '2.4 GHz' },
  },
  {
    name: 'Nivea Body Wash - Men Active Clean',
    brand: 'Nivea',
    category: 'Daily Usage',
    description: 'Refreshing shower gel with active charcoal formula for deep cleansing.',
    price: 249,
    oldPrice: 350,
    stock: 60,
    rating: 4.4,
    images: ['https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=500&auto=format&fit=crop'],
    specifications: { volume: '250ml', scent: 'Fresh' },
  },
  {
    name: 'Colgate MaxFresh Toothpaste',
    brand: 'Colgate',
    category: 'Daily Usage',
    description: 'Fresh breath toothpaste with cooling crystals for intense freshness. Pack of 2.',
    price: 185,
    oldPrice: 220,
    stock: 80,
    rating: 4.5,
    images: ['https://images.unsplash.com/photo-1559599101-3097d66a7c26?w=500&auto=format&fit=crop'],
    specifications: { weight: '300g', flavor: 'Peppermint' },
  },
  {
    name: 'Dettol Liquid Handwash Refill',
    brand: 'Dettol',
    category: 'Daily Usage',
    description: 'Antibacterial liquid soap refill providing 99.9% germ protection.',
    price: 99,
    oldPrice: 119,
    stock: 120,
    rating: 4.6,
    images: ['https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=500&auto=format&fit=crop'],
    specifications: { volume: '175ml', antibacterial: 'Yes' },
  },
  {
    name: 'Head & Shoulders Anti-Dandruff Shampoo',
    brand: 'Head & Shoulders',
    category: 'Daily Usage',
    description: 'Classic clean shampoo that deeply cleanses the scalp and prevents dandruff.',
    price: 340,
    oldPrice: 450,
    stock: 50,
    rating: 4.3,
    images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=500&auto=format&fit=crop'],
    specifications: { volume: '340ml', type: 'Anti-Dandruff' },
  },
  {
    name: 'Gillette Mach3 Turbo Razor',
    brand: 'Gillette',
    category: 'Daily Usage',
    description: "Men's razor with 3 stronger-than-steel blades for a smoother shave.",
    price: 475,
    oldPrice: 550,
    stock: 40,
    rating: 4.5,
    images: ['https://images.unsplash.com/photo-1501250987900-211872d97eaa?w=500&auto=format&fit=crop'],
    specifications: { blades: '3 blades', lubricated: 'Yes' },
  },
  {
    name: 'Park Avenue Signature Deo',
    brand: 'Park Avenue',
    category: 'Daily Usage',
    description: 'Long lasting deodorant spray for men with a rich masculine fragrance.',
    price: 199,
    oldPrice: 250,
    stock: 75,
    rating: 4.2,
    images: ['https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=500&auto=format&fit=crop'],
    specifications: { volume: '150ml', duration: '8 hours' },
  },
  {
    name: 'Himalaya Purifying Neem Face Wash',
    brand: 'Himalaya',
    category: 'Daily Usage',
    description: 'Herbal face wash with neem and turmeric to combat acne and pimples.',
    price: 190,
    oldPrice: 250,
    stock: 90,
    rating: 4.4,
    images: ['https://images.unsplash.com/photo-1556229174-5e42a09e45af?w=500&auto=format&fit=crop'],
    specifications: { volume: '150ml', skinType: 'All' },
  },
  {
    name: 'Ariel Matic Top Load Detergent Powder',
    brand: 'Ariel',
    category: 'Daily Usage',
    description: 'Advanced washing powder designed for top loading washing machines.',
    price: 360,
    oldPrice: 420,
    stock: 35,
    rating: 4.6,
    images: ['https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=500&auto=format&fit=crop'],
    specifications: { weight: '1kg', type: 'Top Load' },
  },
  {
    name: 'Lizol Disinfectant Floor Cleaner',
    brand: 'Lizol',
    category: 'Daily Usage',
    description: 'Citrus floor cleaning liquid that kills 99.9% of germs and leaves a fresh scent.',
    price: 189,
    oldPrice: 215,
    stock: 45,
    rating: 4.5,
    images: ['https://images.unsplash.com/photo-1563453392212-326f5e854473?w=500&auto=format&fit=crop'],
    specifications: { volume: '500ml', fragrance: 'Citrus' },
  },
  {
    name: 'Fortune Premium Kachi Ghani Mustard Oil',
    brand: 'Fortune',
    category: 'Groceries',
    description: 'Pure cold-pressed mustard oil with strong aroma and high pungency.',
    price: 165,
    oldPrice: 195,
    stock: 85,
    rating: 4.5,
    images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&auto=format&fit=crop'],
    specifications: { volume: '1 Litre', type: 'Cold Pressed' },
  },
  {
    name: 'Daawat Rozana Super Basmati Rice',
    brand: 'Daawat',
    category: 'Groceries',
    description: 'Fine quality basmati rice grains perfect for everyday consumption and biryani.',
    price: 379,
    oldPrice: 450,
    stock: 40,
    rating: 4.4,
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop'],
    specifications: { weight: '5kg', grain: 'Long Basmati' },
  },
  {
    name: 'Tata Salt Lite',
    brand: 'Tata',
    category: 'Groceries',
    description: 'Low sodium iodized salt designed for active health management.',
    price: 28,
    oldPrice: 32,
    stock: 200,
    rating: 4.7,
    images: ['https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=500&auto=format&fit=crop'],
    specifications: { weight: '1kg', type: 'Low Sodium' },
  },
  {
    name: 'Ashirvaad Shudh Chakki Atta',
    brand: 'Ashirvaad',
    category: 'Groceries',
    description: '100% pure whole wheat flour processed with traditional stone-grinding.',
    price: 260,
    oldPrice: 299,
    stock: 50,
    rating: 4.6,
    images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop'],
    specifications: { weight: '5kg', source: 'Whole Wheat' },
  },
  {
    name: 'Tata Tea Premium',
    brand: 'Tata',
    category: 'Groceries',
    description: 'Unique blend of big tea leaves and gentle leaves for full body taste and color.',
    price: 145,
    oldPrice: 180,
    stock: 90,
    rating: 4.4,
    images: ['https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=500&auto=format&fit=crop'],
    specifications: { weight: '500g', blend: 'Assam' },
  },
  {
    name: 'Nescafe Classic Instant Coffee',
    brand: 'Nescafe',
    category: 'Groceries',
    description: '100% pure instant coffee powder crafted from selected robusta beans.',
    price: 165,
    oldPrice: 185,
    stock: 80,
    rating: 4.5,
    images: ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop'],
    specifications: { weight: '50g', type: 'Instant' },
  },
  {
    name: 'Kellogg\'s Corn Flakes',
    brand: 'Kelloggs',
    category: 'Groceries',
    description: 'Crispy golden corn flakes packed with essential iron and vitamins.',
    price: 199,
    oldPrice: 240,
    stock: 65,
    rating: 4.3,
    images: ['https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=500&auto=format&fit=crop'],
    specifications: { weight: '475g', flavor: 'Original' },
  },
  {
    name: 'Saffola Gold Cooking Oil',
    brand: 'Saffola',
    category: 'Groceries',
    description: 'Pro-blend edible oil with multi-seed technology and heart health support.',
    price: 149,
    oldPrice: 175,
    stock: 70,
    rating: 4.5,
    images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&auto=format&fit=crop'],
    specifications: { volume: '1 Litre', composition: 'Rice Bran + Safflower' },
  },
  {
    name: 'Amul Pure Ghee',
    brand: 'Amul',
    category: 'Groceries',
    description: 'Rich and granular pure cow ghee made from fresh cream.',
    price: 650,
    oldPrice: 690,
    stock: 45,
    rating: 4.8,
    images: ['https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=500&auto=format&fit=crop'],
    specifications: { volume: '1 Litre', type: 'Cow Ghee' },
  },
  {
    name: 'Cadbury Dairy Milk Silk Chocolate',
    brand: 'Cadbury',
    category: 'Groceries',
    description: 'Smooth and creamy milk chocolate bar, perfect for gifting or snacking.',
    price: 75,
    oldPrice: 80,
    stock: 150,
    rating: 4.6,
    images: ['https://images.unsplash.com/photo-1549007994-cb92ca71450a?w=500&auto=format&fit=crop'],
    specifications: { weight: '60g', flavor: 'Classic Milk' },
  },
  {
    name: 'Sony WH-1000XM5 Wireless Headphones',
    brand: 'Sony',
    category: 'Audio',
    description: 'Industry leading noise cancelling headphones with Alexa built-in.',
    price: 29999,
    oldPrice: 34999,
    stock: 15,
    rating: 4.6,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop'],
    specifications: { ANC: 'Dual Processor', battery: '30 hours' },
  },
  {
    name: 'JBL Flip 6 Portable Bluetooth Speaker',
    brand: 'JBL',
    category: 'Audio',
    description: 'Powerful portable speaker with 2-way speaker system and IP67 waterproof design.',
    price: 9999,
    oldPrice: 13999,
    stock: 25,
    rating: 4.4,
    images: ['https://images.unsplash.com/photo-1589003077984-894e133dabab?w=500&auto=format&fit=crop'],
    specifications: { power: '20W', battery: '12 hours' },
  },
  {
    name: 'Apple AirPods Pro (2nd Generation)',
    brand: 'Apple',
    category: 'Audio',
    description: 'Active noise cancellation, transparency mode, and personalized spatial audio.',
    price: 24900,
    oldPrice: 26900,
    stock: 30,
    rating: 4.7,
    images: ['https://images.unsplash.com/photo-1588449668365-d15e397f6787?w=500&auto=format&fit=crop'],
    specifications: { chip: 'Apple H2', wireless: 'MagSafe' },
  },
  {
    name: 'Bose QuietComfort Earbuds II',
    brand: 'Bose',
    category: 'Audio',
    description: 'Customized active noise cancelling earbuds with world-class quietness.',
    price: 19999,
    oldPrice: 25999,
    stock: 12,
    rating: 4.5,
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500&auto=format&fit=crop'],
    specifications: { ANC: 'CustomTune', battery: '6 hours' },
  },
  {
    name: 'Sennheiser HD 600 Open Back Headphones',
    brand: 'Sennheiser',
    category: 'Audio',
    description: 'Audiophile-grade open-back studio monitoring headphones.',
    price: 27999,
    oldPrice: 32999,
    stock: 8,
    rating: 4.8,
    images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=500&auto=format&fit=crop'],
    specifications: { impedance: '300 Ohm', type: 'Open Back' },
  },
  {
    name: 'Apple Watch Series 9',
    brand: 'Apple',
    category: 'Wearables',
    description: 'S9 SiP chip, double tap gesture, bright Always-On Retina display.',
    price: 41900,
    oldPrice: 44900,
    stock: 14,
    rating: 4.6,
    images: ['https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=500&auto=format&fit=crop'],
    specifications: { screen: 'Always-On Retina', sensors: 'ECG, Blood Oxygen' },
  },
  {
    name: 'Samsung Galaxy Watch 6',
    brand: 'Samsung',
    category: 'Wearables',
    description: 'Advanced sleep coaching, body composition analysis, and heart rhythm alerts.',
    price: 26999,
    oldPrice: 32999,
    stock: 22,
    rating: 4.4,
    images: ['https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=500&auto=format&fit=crop'],
    specifications: { screen: 'Super AMOLED', OS: 'Wear OS' },
  },
  {
    name: 'Fitbit Charge 6 Fitness Tracker',
    brand: 'Fitbit',
    category: 'Wearables',
    description: 'Heart rate tracking, built-in GPS, active zone minutes, and 7-day battery.',
    price: 14999,
    oldPrice: 17999,
    stock: 16,
    rating: 4.2,
    images: ['https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=500&auto=format&fit=crop'],
    specifications: { battery: '7 days', GPS: 'Built-in' },
  },
  {
    name: 'OnePlus Watch 2',
    brand: 'OnePlus',
    category: 'Wearables',
    description: 'Dual-engine architecture, up to 100 hours of battery life in Smart Mode.',
    price: 24999,
    oldPrice: 27999,
    stock: 19,
    rating: 4.5,
    images: ['https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=500&auto=format&fit=crop'],
    specifications: { chip: 'Snapdragon W5', storage: '32GB' },
  },
  {
    name: 'Apple iPhone 15 Pro Max',
    brand: 'Apple',
    category: 'Smartphones',
    description: 'Titanium design, A17 Pro chip, powerful 5x Telephoto camera.',
    price: 148900,
    oldPrice: 159900,
    stock: 10,
    rating: 4.8,
    images: ['https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=500&auto=format&fit=crop'],
    specifications: { chip: 'A17 Pro', camera: '48MP Main' },
  },
  {
    name: 'Samsung Galaxy S24 Ultra',
    brand: 'Samsung',
    category: 'Smartphones',
    description: 'Galaxy AI integration, built-in S Pen, 200MP camera, Snapdragon 8 Gen 3.',
    price: 129999,
    oldPrice: 139999,
    stock: 15,
    rating: 4.7,
    images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=500&auto=format&fit=crop'],
    specifications: { chip: 'Snapdragon 8 Gen 3', camera: '200MP' },
  },
  {
    name: 'OnePlus 12',
    brand: 'OnePlus',
    category: 'Smartphones',
    description: 'Hasselblad camera system, 100W SuperVOOC fast charging.',
    price: 64999,
    oldPrice: 69999,
    stock: 18,
    rating: 4.5,
    images: ['https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=500&auto=format&fit=crop'],
    specifications: { screen: '2K 120Hz AMOLED', battery: '5400 mAh' },
  },
  {
    name: 'Google Pixel 8 Pro',
    brand: 'Google',
    category: 'Smartphones',
    description: 'Google Tensor G3 chip, advanced photo editing features, Magic Eraser.',
    price: 97999,
    oldPrice: 109999,
    stock: 12,
    rating: 4.6,
    images: ['https://images.unsplash.com/photo-1598327106026-d9521da673d1?w=500&auto=format&fit=crop'],
    specifications: { chip: 'Tensor G3', RAM: '12GB' },
  },
  {
    name: 'Apple MacBook Air M3',
    brand: 'Apple',
    category: 'Laptops',
    description: 'Ultra-slim design, Apple M3 chip, up to 18 hours of battery life.',
    price: 114900,
    oldPrice: 124900,
    stock: 10,
    rating: 4.7,
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&auto=format&fit=crop'],
    specifications: { chip: 'Apple M3', RAM: '8GB' },
  },
  {
    name: 'Dell XPS 13 Plus',
    brand: 'Dell',
    category: 'Laptops',
    description: 'Seamless glass touchpad, edge-to-edge keyboard, 13.4-inch OLED display.',
    price: 184999,
    oldPrice: 210000,
    stock: 6,
    rating: 4.3,
    images: ['https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=500&auto=format&fit=crop'],
    specifications: { cpu: 'Intel Core i7', screen: 'OLED Touch' },
  },
  {
    name: 'Asus ROG Zephyrus G14',
    brand: 'Asus',
    category: 'Laptops',
    description: 'Compact gaming laptop with AMD Ryzen 9 and Nvidia RTX 4060 graphics.',
    price: 149999,
    oldPrice: 179999,
    stock: 8,
    rating: 4.6,
    images: ['https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500&auto=format&fit=crop'],
    specifications: { cpu: 'Ryzen 9', gpu: 'RTX 4060' },
  },
  {
    name: 'HP Spectre x360 2-in-1',
    brand: 'HP',
    category: 'Laptops',
    description: 'Convertible touchscreen laptop with stylus support and active cooling.',
    price: 139999,
    oldPrice: 159999,
    stock: 5,
    rating: 4.5,
    images: ['https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500&auto=format&fit=crop'],
    specifications: { screen: '14-inch OLED Touch', type: 'Convertible' },
  },
  {
    name: 'Sony Alpha 7 IV Mirrorless Camera',
    brand: 'Sony',
    category: 'Cameras',
    description: '33MP full-frame Exmor R sensor, hybrid photo and video recording.',
    price: 219990,
    oldPrice: 242490,
    stock: 7,
    rating: 4.8,
    images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500&auto=format&fit=crop'],
    specifications: { sensor: '33MP Full-Frame', video: '4K 60p' },
  },
  {
    name: 'Canon EOS R50',
    brand: 'Canon',
    category: 'Cameras',
    description: 'Compact vlog camera with high-speed autofocus and vertical video support.',
    price: 69990,
    oldPrice: 75990,
    stock: 12,
    rating: 4.4,
    images: ['https://images.unsplash.com/photo-1495707902641-75cac588d2e9?w=500&auto=format&fit=crop'],
    specifications: { sensor: '24.2MP APS-C', screen: 'Vari-angle Touchscreen' },
  },
  {
    name: 'GoPro HERO12 Black',
    brand: 'GoPro',
    category: 'Cameras',
    description: 'Rugged action camera with HyperSmooth 6.0 stabilization and HDR video.',
    price: 37900,
    oldPrice: 45000,
    stock: 15,
    rating: 4.5,
    images: ['https://images.unsplash.com/photo-1565538810844-1e1191b29c07?w=500&auto=format&fit=crop'],
    specifications: { stabilization: 'HyperSmooth 6.0', video: '5.3K 60p' },
  },
  {
    name: 'Apple iPad Air (5th Generation)',
    brand: 'Apple',
    category: 'Tablets',
    description: 'M1 chip, 10.9-inch Liquid Retina display, Center Stage camera.',
    price: 59900,
    oldPrice: 69900,
    stock: 11,
    rating: 4.6,
    images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500&auto=format&fit=crop'],
    specifications: { chip: 'Apple M1', screen: '10.9 inch' },
  },
  {
    name: 'Samsung Galaxy Tab S9 Ultra',
    brand: 'Samsung',
    category: 'Tablets',
    description: 'Massive 14.6-inch Dynamic AMOLED 2X screen, IP68 water resistance, S Pen.',
    price: 108999,
    oldPrice: 121999,
    stock: 9,
    rating: 4.7,
    images: ['https://images.unsplash.com/photo-1561154464-82e9adf32764?w=500&auto=format&fit=crop'],
    specifications: { screen: '14.6 inch', stylus: 'Included' },
  },
  {
    name: 'Lenovo Tab P12',
    brand: 'Lenovo',
    category: 'Tablets',
    description: '12.7-inch 3K screen, Octa-core processor, quad JBL speakers.',
    price: 26999,
    oldPrice: 34999,
    stock: 14,
    rating: 4.3,
    images: ['https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?w=500&auto=format&fit=crop'],
    specifications: { screen: '12.7 inch 3K', audio: 'Quad JBL' },
  },
  {
    name: 'Logitech MX Master 3S Mouse',
    brand: 'Logitech',
    category: 'Accessories',
    description: 'Ergonomic wireless mouse with 8K DPI tracking and silent clicks.',
    price: 9495,
    oldPrice: 10995,
    stock: 20,
    rating: 4.7,
    images: ['https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=500&auto=format&fit=crop'],
    specifications: { DPI: '8000', battery: '70 days' },
  },
  {
    name: 'Seagate Expansion 2TB External HDD',
    brand: 'Seagate',
    category: 'Accessories',
    description: 'Portable external hard drive with high-speed USB 3.0 connectivity.',
    price: 5999,
    oldPrice: 7999,
    stock: 35,
    rating: 4.3,
    images: ['https://images.unsplash.com/photo-1601524909162-be87252be298?w=500&auto=format&fit=crop'],
    specifications: { capacity: '2TB', interface: 'USB 3.0' },
  },
  {
    name: 'Sony PlayStation 5 Slim',
    brand: 'Sony',
    category: 'Gaming',
    description: 'Slim design console with ultra-high speed SSD and haptic feedback.',
    price: 44990,
    oldPrice: 54990,
    stock: 15,
    rating: 4.8,
    images: ['https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=500&auto=format&fit=crop'],
    specifications: { storage: '1TB SSD', rayTracing: 'Yes' },
  },
  {
    name: 'Razer DeathAdder V3 Pro',
    brand: 'Razer',
    category: 'Gaming',
    description: 'Ultra-lightweight wireless gaming mouse with 63g build and optical switches.',
    price: 13999,
    oldPrice: 15999,
    stock: 12,
    rating: 4.6,
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&auto=format&fit=crop'],
    specifications: { weight: '63g', switches: 'Razer Optical Gen 3' },
  },
  {
    name: 'Anker 3-in-1 Charging Cube',
    brand: 'Anker',
    category: 'Accessories',
    description: 'MagSafe compatible 15W wireless charging cube for phone, watch, and pods.',
    price: 12999,
    oldPrice: 14999,
    stock: 10,
    rating: 4.4,
    images: ['https://images.unsplash.com/photo-1622445262465-2481c4574875?w=500&auto=format&fit=crop'],
    specifications: { power: '15W MagSafe', fold: 'Yes' },
  },
  {
    name: 'TP-Link Deco X50 Mesh Wi-Fi',
    brand: 'TP-Link',
    category: 'Accessories',
    description: 'Whole home mesh Wi-Fi 6 system with speeds up to 3000 Mbps. Pack of 2.',
    price: 13999,
    oldPrice: 18999,
    stock: 8,
    rating: 4.5,
    images: ['https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=500&auto=format&fit=crop'],
    specifications: { standard: 'Wi-Fi 6', speed: '3000 Mbps' },
  },
  {
    name: 'Elgato Stream Deck MK.2',
    brand: 'Elgato',
    category: 'Gaming',
    description: 'Studio controller with 15 customizable LCD keys for streaming.',
    price: 14999,
    oldPrice: 16999,
    stock: 15,
    rating: 4.7,
    images: ['https://images.unsplash.com/photo-1616440347437-b1c73416efc2?w=500&auto=format&fit=crop'],
    specifications: { keys: '15 LCD keys', connection: 'USB-C' },
  },
]
